version: '3.6'
services:
  postgres2:
    image: postgres:9.6
    ports:
    - "5432:5432"
    environment:
    - "POSTGRES_PASSWORD:dalong"
    volumes:
    - ./db_data2:/var/lib/postgresql/data
  postgres:
    image: postgres:9.6
    ports:
    - "5435:5432"
    environment:
    - "POSTGRES_PASSWORD:dalong"
    volumes:
    - ./db_data:/var/lib/postgresql/data
  benthos:
    image: jeffail/benthos
    volumes:
    - "./configs/webhook.yaml:/benthos.yaml"
    ports:
    - "4195:4195"
  node-exress:
    image: dalongrong/stitchmerge
    ports:
    - "3000:3000"
  graphql-engine2:
    image: hasura/graphql-engine:v1.0.0-alpha30
    ports:
    - "8080:8080"
    depends_on:
    - "postgres"
    environment:
    - "POSTGRES_PASSWORD:dalong"
    command: >
      /bin/sh -c "
      graphql-engine --database-url postgres://postgres:dalong@postgres2:5432/postgres serve --enable-console;
      "
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-alpha29
    ports:
    - "8090:8080"
    depends_on:
    - "postgres"
    environment:
    - "POSTGRES_PASSWORD:dalong"
    command: >
      /bin/sh -c "
      graphql-engine --database-url postgres://postgres:dalong@postgres:5432/postgres serve --enable-console;
      "